tighten Representable version
representable 3.1 may contain breaking changes

We caught the following error on representable 3.1.1:

```
Error: test: normal invoke with AggregateRequest model(TestClient::#invoke): ArgumentError: wrong number of arguments (given 1, expected 2)
/Users/taka/work/ruby/octoparts-rb/lib/octoparts/representer/aggregate_request_representer.rb:11:in `call'
/Users/taka/work/ruby/octoparts-rb/vendor/bundle/ruby/2.6.0/gems/trailblazer-option-0.1.1/lib/trailblazer/option.rb:15:in `public_send'
```

This is not happen on 3.0.4 therefore the following 3.1's change might
affect the behavior.

> Replace declarative-option with trailblazer-option

https://github.com/trailblazer/representable/blob/dd499610f7442c30169f51f270ba5fa2252d2bad/CHANGES.md#310